### ISSUE TITLE
Is there plan to put this on to hex.pm?

### ISSUE THREAD

**Issue by yuchunc** [eyrmedical/opentok#1]
Hi,

I'm poking with a new project idea, and thinking about using tokbox's service. Since this is the only opentok elixir sdk out there, I'm wondering is there any plan on putting this on to hex.pm.

thank you!

**Comment by Voronchuk** [comment]
Hi,

We don’t plan to support this as we are in a process of writing pure Elixir
signaling server.

Regards,
V

**Comment by yuchunc** [comment]
Ah very cool, best of luck on the new project!
